version: "3"
services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - BACKEND_URI=http://localhost:5000
    depends_on:
      - graphql
  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: example
      POSTGRES_DB: example
  
  graphql:
    build:
      context: ./graphql
    ports:
      - "5000:5000"
    #network_mode: "host"

    environment:
      - DATABASE_URL=postgres://postgres:example@db:5432/example
      - CORS_ORIGIN=http://localhost/3000
      - APOLLO_PORT=5000
    depends_on:
      - db
    links:
      - db
  whois:
    build:
      context: ./whois
    ports:
      - "${FLASK_PORT:-5001}:${FLASK_PORT:-5001}"
    environment:
      - GEOIP_USER_ID=${GEOIP_USER_ID}
      - GEOIP_LICENSE_KEY=${GEOIP_LICENSE_KEY}
      - PORT=${FLASK_PORT:-5001}
      - GEOIP_DIRECTORY=/app/GeoIP

  unit-test:
    image: node:latest
    working_dir: /app
    volumes:
      - ./:/app
    command: ["yarn", "test"]
    environment:
      - NODE_ENV=test
    depends_on:
      - graphql