services:
  backend:
    image: node:latest
    tty: true
    container_name: helpdesk-backend
    build:
      context: .
      dockerfile: Dockerfile_Back
    expose:
      - 8080
      - 6379
    ports:
      - 127.0.0.1:8080:8080
    volumes:
      - .:/helpbackend
    environment:
    - JWT_SECRET=FartyFartls
    - REDIS_URL=redis://redis:6379
    - NODE_ENV=production
    - VIRTUAL_HOST=helpbackend.or9.ca
  redis:
    image: redis:alpine
    container_name: redis
    expose:
      - 6379
    ports:
      - 127.0.0.1:6379:6379
    environment:
      - VIRTUAL_HOST=helpbackend.or9.ca
