version: "3"
services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - BACKEND_URI=http://graphql:5000
    depends_on:
      - graphql
    networks:
      - frontend-to-graphql
  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: example
      POSTGRES_DB: example
    networks:
      - graphql-to-db
  
  graphql:
    build:
      context: ./graphql
    ports:
      - "5000:5000"
    #network_mode: "host"

    environment:
      - DATABASE_URL=postgres://postgres:example@db:5432/example
      - CORS_ORIGIN=http://frontend/3000
      - APOLLO_PORT=5000
      - L_API_URL=http://whois:5001
      - NODE_ENV=dev
    depends_on:
      - db
    networks:
      - graphql-to-db
      - frontend-to-graphql
      - graphql-to-whois
  whois:
    build:
      context: ./whois
    ports:
      - "${FLASK_PORT:-5001}:${FLASK_PORT:-5001}"
    environment:
      - GEOIP_USER_ID=${GEOIP_USER_ID}
      - GEOIP_LICENSE_KEY=${GEOIP_LICENSE_KEY}
      - PORT=${FLASK_PORT:-5001}
      - GEOIP_DIRECTORY=/app/GeoIP
    networks:
      - graphql-to-whois

  unit-test:
    image: node:latest
    working_dir: /app
    volumes:
      - ./:/app
    command: ["yarn", "test"]
    environment:
      - NODE_ENV=test
    depends_on:
      - graphql
    networks:
      - frontend-to-graphql


networks:
  frontend-to-graphql:
  graphql-to-db:
  graphql-to-whois: