[build]
  base = "./graphql"
  command = "npm install && npm run tsc"
  publish = "/"


[context.branch-deploy.environment]
  NODE_ENV = "development"
  environment = { NODE_VERSION = "18.14.2" }

# Dev context: environment variables set here 
# are available for local development environments 
# run using Netlify Dev. These values can be 
# overwritten on branches that have a more specific 
# branch context configured.
[context.dev.environment]
  NODE_ENV = "development"
  environment = { NODE_VERSION = "18.14.2" }

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/api/*"
  to = "http://localhost:5000/:splat"
  status = 200
  

[[redirects]]
  from = "/"
  to = "/index.html"
  status = 200

[dev]
  command = "npx index.js"
  port = 5000
