[build]
  base = "./graphql"
  command = "npm install && npm run tsc && node index.js &"
  publish = "/graphql"

[[redirects]]
  from = "/*"
  to = "/index.js"
  status = 200

[[redirects]]
  from = "/api/*"
  to = "http://localhost:5000/:splat"
  status = 200
