version: "3"
services:
  whois:
      build:
        context: .
      ports:
        - "5000:5000"
      environment:
        - GEOIP_USER_ID=832978
        - GEOIP_LICENSE_KEY=9E7E2BCtGW4Prbre
        - PORT=5000
        - GEOIP_DIRECTORY=/app/GeoIP