version: "3"
services:
  whois:
      build:
        context: .
      ports:
        - "${FLASK_PORT:-5001}:${FLASK_PORT:-5001}"
      environment:
        - GEOIP_USER_ID=${{ secrets.GEOIP_USER_ID }}
        - GEOIP_LICENSE_KEY=${{ secrets.GEOIP_LICENSE_KEY }}
        - PORT=${FLASK_PORT:-5001}
        - GEOIP_DIRECTORY=/app/GeoIP