name: Build and publish Docker images as GitHub Artifacts

on:
  push:
    branches:
      - main

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build and save frontend image
        id: frontend
        run: |
          docker build -t frontend:latest ./frontend
          docker tag frontend:latest frontend:${{ github.sha }}
          docker save frontend:${{ github.sha }} > frontend.tar
          echo ${{ github.sha }} >> sha.txt
        continue-on-error: true

      - name: Build and save graphql image
        id: graphql
        run: |
          docker build -t graphql:latest ./graphql
          docker tag graphql:latest graphql:${{ github.sha }}
          docker save graphql:${{ github.sha }} > graphql.tar
          echo ${{ github.sha }} >> sha.txt
        continue-on-error: true

      - name: Build and save whois image
        id: whois
        run: |
          docker build -t whois:latest ./whois
          docker tag whois:latest whois:${{ github.sha }}
          docker save whois:${{ github.sha }} > whois.tar
          echo ${{ github.sha }} >> sha.txt
        continue-on-error: true

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: docker-images
          path: |
            sha.txt
            frontend.tar
            whois.tar
            graphql.tar
